// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWMEOggsgeY_PWh3e0JhLksnQ-cJM6dt4',
    appId: '1:235371706191:web:ad5df31c00e9a00bc6b73a',
    messagingSenderId: '235371706191',
    projectId: 'task-e9ecb',
    authDomain: 'task-e9ecb.firebaseapp.com',
    storageBucket: 'task-e9ecb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Pff2mTQ_PcTelVt1iEELNu3bdj-5MxE',
    appId: '1:235371706191:android:d1d916a383f5d0a3c6b73a',
    messagingSenderId: '235371706191',
    projectId: 'task-e9ecb',
    storageBucket: 'task-e9ecb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD0-BlJOUot9Q5I9iEJWWH35cWBFEcA_U',
    appId: '1:235371706191:ios:670f489644ad6bf5c6b73a',
    messagingSenderId: '235371706191',
    projectId: 'task-e9ecb',
    storageBucket: 'task-e9ecb.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD0-BlJOUot9Q5I9iEJWWH35cWBFEcA_U',
    appId: '1:235371706191:ios:670f489644ad6bf5c6b73a',
    messagingSenderId: '235371706191',
    projectId: 'task-e9ecb',
    storageBucket: 'task-e9ecb.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWMEOggsgeY_PWh3e0JhLksnQ-cJM6dt4',
    appId: '1:235371706191:web:ce043b41b47eeb47c6b73a',
    messagingSenderId: '235371706191',
    projectId: 'task-e9ecb',
    authDomain: 'task-e9ecb.firebaseapp.com',
    storageBucket: 'task-e9ecb.firebasestorage.app',
  );
}
